# Auto-generated by .github/workflows/release.yml — do not edit by hand.
class Asindie < Formula
  desc "AsIndie game distribution CLI"
  homepage "https://asindie.com"
  version "0.4.6"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://releases.asindie.com/cli/0.4.6/asindie-macos-arm64"
      sha256 "4ff5df96fafc387a4ff9f8044de77b02caa717e8a030caab67437e2d12de420a"
    end
    on_intel do
      url "https://releases.asindie.com/cli/0.4.6/asindie-macos-x64"
      sha256 "8b6c95d28dff79ff845612ccceb5fb494d95a13a2c31b7f3598166e3941562b1"
    end
  end

  on_linux do
    # Sadece x86_64. ARM Linux v0.5.0'da geri eklenecek.
    url "https://releases.asindie.com/cli/0.4.6/asindie-linux-x64"
    sha256 "e33a2534e7f6023f9a79f3d313d823a6fd1b544bd40db7cfce8ca4cb80b2e64a"
  end

  def install
    # Asset isim olarak indirilir (asindie-macos-arm64 vs.) — rename + chmod
    binary = Dir["asindie-*"].first
    chmod 0755, binary
    bin.install binary => "asindie"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/asindie --version")
  end
end
