# Auto-generated by .github/workflows/release.yml — do not edit by hand.
class Asindie < Formula
  desc "AsIndie game distribution CLI"
  homepage "https://asindie.com"
  version "0.4.5"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://releases.asindie.com/cli/0.4.5/asindie-macos-arm64"
      sha256 "32610fd3fba4cc349e87c4e0b493abf633e6939ab1cda2a19e8830fe856c04b8"
    end
    on_intel do
      url "https://releases.asindie.com/cli/0.4.5/asindie-macos-x64"
      sha256 "c5ebaf7e3275f73d67ddf1e8fd027061dde940ce4ce10484219a7f05ebf23562"
    end
  end

  on_linux do
    # Sadece x86_64. ARM Linux v0.5.0'da geri eklenecek.
    url "https://releases.asindie.com/cli/0.4.5/asindie-linux-x64"
    sha256 "d42fcc9e9894c62563f2be1c090459cf739271c0c61a6f962399b941811d52b5"
  end

  def install
    # Asset isim olarak indirilir (asindie-macos-arm64 vs.) — rename + chmod
    binary = Dir["asindie-*"].first
    chmod 0755, binary
    bin.install binary => "asindie"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/asindie --version")
  end
end
